apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: predict-ingress
  namespace: mlflow-stack
spec:
  rules:
    # Puedes definir un host si ya tienes uno configurado con tu dominio.
    # - host: ml.example.com
    - http:
        paths:
          - path: /predict
            pathType: Prefix
            backend:
              service:
                name: predict
                port:
                  number: 8080
    - http:
        paths:
          - path: /predict_winner
            pathType: Prefix
            backend:
              service:
                name: predict
                port:
                  number: 8080