apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlruns-pvc
  namespace: mlflow-stack
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-cache-pvc
  namespace: mlflow-stack
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
