apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-predictor
  namespace: ${NAMESPACE:-f1-predictor}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f1-predictor
  template:
    metadata:
      labels:
        app: f1-predictor
    spec:
      containers:
      - name: f1-predictor
        image: ${DOCKER_REGISTRY}/f1-predictor:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: f1-predictor
  namespace: ${NAMESPACE:-f1-predictor}
spec:
  selector:
    app: f1-predictor
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
