apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-trainer
  namespace: ${NAMESPACE:-f1-predictor}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f1-trainer
  template:
    metadata:
      labels:
        app: f1-trainer
    spec:
      containers:
      - name: f1-trainer
        image: ${DOCKER_REGISTRY}/f1-trainer:latest
        ports:
        - containerPort: 8001
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: model-volume
          mountPath: /app/model.pkl
          subPath: model.pkl
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: f1-data-pvc
      - name: model-volume
        persistentVolumeClaim:
          claimName: f1-model-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: f1-trainer
  namespace: ${NAMESPACE:-f1-predictor}
spec:
  selector:
    app: f1-trainer
  ports:
  - port: 80
    targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f1-data-pvc
  namespace: ${NAMESPACE:-f1-predictor}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f1-model-pvc
  namespace: ${NAMESPACE:-f1-predictor}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi