apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-race-predictor
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f1-race-predictor
  template:
    metadata:
      labels:
        app: f1-race-predictor
    spec:
      containers:
        - name: front
          image: f1predictoracr.azurecr.io/frontend/predictorfrontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-config
            - secretRef:
                name: frontend-secret
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
            # initialDelaySeconds: 30
            # periodSeconds: 20
      imagePullSecrets:
        - name: acr-secret
      # restartPolicy: Always