apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: train-ingress
  namespace: mlflow-stack
spec:
  rules:
    # Descomenta y reemplaza si tienes un dominio configurado
    # - host: ml.example.com
    - http:
        paths:
          - path: /train
            pathType: Prefix
            backend:
              service:
                name: train
                port:
                  number: 7000